// GENERATED FILE. DO NOT EDIT.
// This file is generated by the migrations tool for PixelTime on 2025-12-08T10:25:54.384637.

import 'migration_model.dart';

const migrations = [
	Migration(
    version: 1764422495047,
    data: r'''CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CONSTRAINT projects_name_unique UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_projects_name ON projects (name);
CREATE INDEX IF NOT EXISTS idx_projects_description ON projects (description);''',
  ),
	Migration(
    version: 1764707440151,
    data: r'''CREATE TABLE IF NOT EXISTS layers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  project_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  visible BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_layers_project_id ON layers (project_id);
CREATE INDEX IF NOT EXISTS idx_layers_position ON layers (position);
CREATE INDEX IF NOT EXISTS idx_layers_visible ON layers (visible);''',
  ),
];