// GENERATED FILE. DO NOT EDIT.
// This file is generated by the migrations tool for PixelTime on 2025-11-29T10:36:13.788091.

import 'migration_model.dart';

const migrations = [
	Migration(
    version: 1764422495047,
    upData: r'''CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_name ON projects (name);
CREATE INDEX IF NOT EXISTS idx_projects_description ON projects (description);''',
    downData: r'''DROP INDEX IF EXISTS idx_projects_name;
DROP INDEX IF EXISTS idx_projects_description;
DROP TABLE IF EXISTS projects;''',
  ),
];