// GENERATED FILE. DO NOT EDIT.
// This file is generated by the migrations tool for PixelTime on 2025-11-30T18:15:31.435376.

import 'migration_model.dart';

const migrations = [
	Migration(
    version: 1764422495047,
    data: r'''CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CONSTRAINT projects_name_unique UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS idx_projects_name ON projects (name);
CREATE INDEX IF NOT EXISTS idx_projects_description ON projects (description);''',
  ),
];