ALTER TABLE layers ADD COLUMN width INTEGER DEFAULT 100;
ALTER TABLE layers ADD COLUMN height INTEGER DEFAULT 100;
ALTER TABLE layers ADD COLUMN x INTEGER DEFAULT 0;
ALTER TABLE layers ADD COLUMN y INTEGER DEFAULT 0;
ALTER TABLE layers ADD COLUMN data BLOB;

CREATE INDEX IF NOT EXISTS idx_layers_width ON layers (width);
CREATE INDEX IF NOT EXISTS idx_layers_height ON layers (height);
CREATE INDEX IF NOT EXISTS idx_layers_x ON layers (x);
CREATE INDEX IF NOT EXISTS idx_layers_y ON layers (y);